Frontend | Add ContactsPage
DJWOMS/GSpot pull request #124
Opened 2023-04-14 12:33 UTC by KarolinaEsepenok

Не знаю, правильно ли разместила в папках(может надо было в features?). Использовала Controller вместо forwardRef (ворнинг остался, но функционал начал работать). Обработку ошибок сделала на свой взгляд, так как в макете четко не описано, потом поменяю, когда нужно будет.

2023-04-14 20:42 UTC, kieled requested changes

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.module.scss
> +    }
md:w-full

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +            {errors.message ? <p className={s.errorMessage}>{errors.message.message}</p> : <p className={s.emptyBlock}></p>}
тут компонент не является кастомным React компонентом, поэтому можно разворачивать `{...register('message')}` вместо конструкции `Controller`

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +          <form className={s.form} action="#" onSubmit={handleSubmit(onSubmit)}>
чтобы не заниматься дополнительной типизацией здесь можно было использовать конструкцию `handleSubmit(({data} => onSubmit(data)))`. Таким образом на вход компоненту сразу поступит объект `FormProps`. Обработка ошибок здесь является излишней, т.к. мы определяем филды `error` и подсвечиваем поля с ошибками

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +    reset({ name: '', email: '', message: '', subject: '' })
достаточно написать `reset()` для сброса всех филдов к `initialState`

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +    'https://maps.google.com/maps?q=221B+Baker+Street,+London,+United+Kingdom&amp;hl=en&amp;t=v&amp;hnear=221B+Baker+St,+London+NW1+6XE,+United+Kingdom'
эту константу желательно обозвать капсом и поместить в папку с глобальными константами, там где находится `API_URL`

2023-04-14 20:42 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +  const disabled = !!errors.name || !!errors.email || !!errors.message || !!errors.subject
приведение в булевому типу здесь не обязательно, т.е. от всех `!!` можно избавиться, в данном случае оно автоматически приведется к нему

2023-04-14 20:45 UTC, kieled requested changes

2023-04-14 20:45 UTC, kieled commented on frontend/components/Footer/Footer.tsx
> +              <a href="/contacts">Контакты</a>
т.к. ссылка ведет на внутренний компонент, необходимо заменить `a` на `Link` из `next`

2023-04-14 21:08 UTC, KarolinaEsepenok commented on frontend/app/(main)/contacts/page.tsx
> +  const disabled = !!errors.name || !!errors.email || !!errors.message || !!errors.subject
Если не привожу к булевому типу, подчеркивает красным, и пишет:TS2322: Type 'FieldError | undefined' is not assignable to type 'boolean | undefined'.   Type 'FieldError' is not assignable to type 'boolean | undefined'.  index.d.ts(2082, 9): The expected type comes from property 'disabled' which is declared here on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'. Но проект запускается и все работает.

2023-04-14 21:16 UTC, KarolinaEsepenok commented on frontend/app/(main)/contacts/page.tsx
> +          <form className={s.form} action="#" onSubmit={handleSubmit(onSubmit)}>
Использовала, но типизацию все равно требует.

2023-04-15 08:51 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +  const disabled = !!errors.name || !!errors.email || !!errors.message || !!errors.subject
ок, оставляй значит как есть. Я потом гляну

2023-04-15 08:53 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +          <form className={s.form} action="#" onSubmit={handleSubmit(onSubmit)}>
типизация для компонента в такум случае будет просто FormProps без доп. импортов

2023-04-15 09:59 UTC, paqstd-dev requested changes

2023-04-15 09:59 UTC, paqstd-dev commented on frontend/app/(main)/contacts/page.module.scss
> +}
Это можно объединить примерно так:
```scss
.contacts {
    @apply ...;

    &Form { ... }
    &Info { ... }
    &List { ... }
}
```

2023-04-15 09:59 UTC, paqstd-dev commented on frontend/app/(main)/contacts/page.tsx
> +          <form className={s.form} action="#" onSubmit={handleSubmit(onSubmit)}>
Лучше всего делать как раз `handleSubmit(onSubmit)`. Это позволяет отделить рендер от логики.

2023-04-15 09:59 UTC, paqstd-dev commented on frontend/app/(main)/contacts/page.tsx
> +            {errors.email ? <p className={s.errorMessage}>{errors.email.message}</p> : <p className={s.emptyBlock}></p>}
Не совсем понятно, зачем существует `<p className={s.emptyBlock}></p>`?

В jsx можно делать вот так:
```jsx
{errors.email && <p>{errors.email.message}</p>}
```

Таким образом мы даже не показываем ничего если все ок, если есть ошибка показываем ошибку. Посмотри в нескольких других местах этого файла такое встречается.

2023-04-15 10:31 UTC, KarolinaEsepenok commented on frontend/app/(main)/contacts/page.tsx
> +            {errors.email ? <p className={s.errorMessage}>{errors.email.message}</p> : <p className={s.emptyBlock}></p>}
Когда делала так как ты написал, то инпуты прыгают при появлении ошибки. <p className={s.emptyBlock}></p> задает высоту блока, чтобы ничего не дергалось.

2023-04-15 10:43 UTC, kieled commented on frontend/app/(main)/contacts/page.tsx
> +            {errors.email ? <p className={s.errorMessage}>{errors.email.message}</p> : <p className={s.emptyBlock}></p>}
тогда лучше не делать отдельный класс, а регулировать только содержимое тега `<p>`. Как вариант чтобы ничего не прыгало установить для класса `errorMessage` аттрибут `min-height`.
Код будет выглядеть следующим образом:
```
<p className={s.errorMessage}>{errors.email ?? errors.email.message}</p>
```

2023-04-15 11:28 UTC, KarolinaEsepenok commented on frontend/app/(main)/contacts/page.module.scss
> +}
Объединила, но немного иначе.

2023-04-15 12:31 UTC, paqstd-dev commented
Запустил локально, посмотрел. 
Нужно использовать https://react-hook-form.com/api/useformstate/errormessage/ для отображения сообщений об ошибке. То что поля "прыгают" при отображении ошибки, это нормальная практика. По ссылке можно посмотреть примеры для отображения одной ошибки, или нескольких сразу для поля. 

Для того, чтобы добавить пустое пространство между инпутами можно использовать `flex flex-col gap-[number]`.

2023-04-15 17:01 UTC, KarolinaEsepenok commented
При использовании https://react-hook-form.com/api/useformstate/errormessage/ необходимо установить это: npm install @hookform/error-message. Мне можно это самой сделать?

2023-04-15 18:31 UTC, paqstd-dev commented
> При использовании https://react-hook-form.com/api/useformstate/errormessage/ необходимо установить это: npm install @hookform/error-message. Мне можно это самой сделать?

Да можно устанавливать библиотеки, которые нужны для реализации функционала.

2023-04-15 18:33 UTC, paqstd-dev commented
Давай сразу сделаем отправку формы на сервер. Для этого нужно в mocks папке создать endpoint, который будет обрабатывать POST запрос (более подробно про это смотри в CONTRIBUTING.md файле). Если все ок (сервер возвращает статус 200), показываем сообщение пользователю что мол "все ок, отправили сообщение".

2023-04-15 19:42 UTC, KarolinaEsepenok commented
Да, хорошо, сделаю отправку формы на сервер(но только понед-вторник, завтра ничего не смогу сделать). А сообщение пользователю(если ок) пока что просто алерт? Я не нашла общую обработку ошибок запросов на сервер, если она есть, то подскажи, пожалуйста, где ее найти). А если не ок, то ничего пока не показывать?

2023-04-15 19:47 UTC, KarolinaEsepenok commented
Да, хорошо, сделаю отправку формы на сервер(но только понед-вторник, завтра ничего не смогу сделать). А сообщение пользователю(если ок) пока что просто алерт? Я не нашла общую обработку ошибок запросов на сервер, если она есть, то подскажи, пожалуйста, где ее найти(ну или мне просто надо поближе познакомиться с nextJS))). А если не ок, то ничего пока не показывать?

2023-04-20 11:43 UTC, paqstd-dev submitted a review, later dismissed
Features создаем только для больших разделов сайта (Domain-driven design), таких как profile, games и тд. В твоем случае contacts это обычная страница, которая принимает данные в форме.

2023-04-20 11:43 UTC, paqstd-dev commented on frontend/app/(main)/contacts/page.tsx
> +  }
Не совсем понятно, зачем `ContactsFormInterface` тут используется? Таким образом ты указываешь тип данных, который будет возвращен в этом запросе. Если смотреть mocks функцию POST, ты возвращаешь {message: string}, можно в этом случае вообще ничего не возвращать в mocks, просто статус 201. Тогда и интерфейс не нужен.

2023-04-20 11:43 UTC, paqstd-dev commented on frontend/app/(main)/contacts/page.tsx
> +    required: true,
Если пользователь ничего не ввел в текстовые поля, должна показываться ошибка. Пока что ничего не отображается. 

Чтобы исправить это, можно указать текст ошибки:
```tsx

const rules = {
    required: 'Поле обязательно',
    ...
}
```

Точно также и с `rulesForEmail`.

2023-04-20 16:24 UTC, kieled reviewed
проверил, всё ок, ждем решения с версией next

2023-04-20 16:35 UTC, kieled approved these changes

2023-04-20 16:36 UTC, merged