Frontend | Favorite Game Card Page
DJWOMS/GSpot pull request #134
Opened 2023-04-15 18:47 UTC by JulieBenchuk

Added actionType ('favorite' | 'delete') to GameCardInterface. Action button in GameCard (delete, buy or none) depends on actionType.

2023-04-17 13:53 UTC, paqstd-dev requested changes
Нужно использовать существующий интерфейс `GameCardInterface`. Добавить ссылку для перехода на страницу с избранными играми. Еще стоит уточнить у команды games, нужен ли фильтр на этой странице, делают ли они его, будут ли делать? 

Дополнительно необходимо реализовать обработчик для кнопки "удалить". Делается запрос на сервер, после успешного ответа необходимо выполнить [мутацию](https://beta.nextjs.org/docs/data-fetching/mutating). Базово можно сделать endpoint в папке mocks, чтобы обработать такой запрос.

2023-04-17 13:53 UTC, paqstd-dev commented on frontend/features/games/components/GameCard/GameCard.tsx
> +        )}
Лучше сделать по другому, передается `favorite` и если он `true`, показываем кнопку Удалить иначе Добавить в избранное (svg значки). Для значка удаления нужно использовать [IconTrash](https://tabler-icons.io/i/trash). 

Интерфейс для такого компонента может расширять интерфейс GameCardInterface, добавляя favorite. Такой интерфейс можно писать сразу возле компонента (в этом же файле).

2023-04-17 13:53 UTC, paqstd-dev commented on frontend/app/(main)/profile/favorites/page.tsx
> +import s from 'app/(main)/catalog/page.module.scss'
Импорт должен быть из файла `./page.module.scss`

2023-04-17 13:53 UTC, paqstd-dev commented on frontend/app/(main)/profile/favorites/page.module.scss
В этом файле должны быть стили для страницы.

2023-04-17 13:53 UTC, paqstd-dev commented on frontend/features/profile/types/index.ts
> +}
Я думаю нет необходимости создавать отдельный interface для списка избранных игр. Это та же карточка, что и GameCard и интерфейс тот же.

2023-04-20 15:46 UTC, kieled submitted a review, later dismissed

2023-04-20 15:46 UTC, kieled commented on frontend/features/games/components/GameCard/GameCard.tsx
> +    })
Весь `useTransition` отсюда нужно убрать. Далее нужно выкинуть наружу метод `onDelete` или что-то вроде того, и на верхнем уровне обрабатывать это действие в компоненте `frontend/app/(main)/profile/favorites/page.tsx`. Там можно реализовать простой фильтр по `id`

2023-04-20 15:46 UTC, kieled commented on frontend/app/(main)/profile/favorites/page.tsx
> +    </>
тут можно убрать полностью `<></>` фрагменты, а так же объединить две `Section` в одну

2023-04-20 15:46 UTC, kieled commented on frontend/app/(main)/profile/favorites/page.tsx
> +  })
вот здесь можно добавить функцию `onDelete` и повесить её при маппинге `GameCard` подвязав айдишник игры

2023-04-20 19:52 UTC, paqstd-dev commented on frontend/app/(main)/profile/favorites/page.tsx
> +  })
Тогда можно не добавлять `favorite` для GameCard. Сделать проверку если есть функция `onDelete`, значит показываем кнопку удаления.

2023-04-20 19:59 UTC, paqstd-dev commented on frontend/features/profile/mocks/index.ts
> +})
Эту функцию лучше убрать. Данные об игре можно сразу создавать `generateMockGameCard()` в mocks.

2023-04-21 13:21 UTC, JulieBenchuk commented on frontend/app/(main)/profile/favorites/page.tsx
> +  })
передавать id игры и реализовать фильтрацию при удалении пока не получается, т.к. интерфейс игры не содержит свойства id. onDelete вынесла в компоненту выше. данные получем в useEffect, т.к. click handler и router требуют клиентскую компоненту (use client). А в клиентской компоненте происходят непрерывные запросы на сервер вне useEffect

2023-04-21 18:15 UTC, paqstd-dev reviewed
router.refresh() будет работать если делается запрос на сервера, согласно докам. 
Я предлагаю принять этот пр. В дальнейшем проработаем это.

2023-04-21 18:17 UTC, paqstd-dev approved these changes

2023-04-22 18:21 UTC, merged