Users: Added jwt_create function
DJWOMS/GSpot pull request #145
Opened 2023-04-18 11:50 UTC by kindevelopment

Add djoser, simple_jwt, create fucntion for create_jwt

2023-04-18 18:05 UTC, egorFilippo requested changes

2023-04-18 18:05 UTC, egorFilippo commented on backend/users/backend/service/jwt/get_permissions.py
> +def get_dict_of_user_permissions(user):
давай описание добавим с примером структуры, которая будет на выходе

2023-04-18 18:05 UTC, egorFilippo commented on backend/users/backend/service/jwt/create_jwt.py
> +def get_token_user(user, role):
давай переименуем. get_token_for_user

2023-04-18 18:05 UTC, egorFilippo commented on backend/users/backend/developers/models.py
> +class CompanyContact(models.Model):
зачем модельки вверх вынес?

2023-04-22 12:26 UTC, egorFilippo approved these changes

2023-04-23 11:01 UTC, mozambique-ya approved these changes
принимаю PR, т.к. есть модели бд, и хоть что-то есть. Но в будущем очень много будем исправлять.

2023-04-23 11:01 UTC, merged