user form validation on page profile/settings, added paralels routing
DJWOMS/GSpot pull request #148
Opened 2023-04-18 18:51 UTC by NikolayN-ru

2023-04-19 10:18 UTC, paqstd-dev requested changes
Обрати внимание на [документацию](https://react-hook-form.com/api/useform/) по `react-hook-form` - в некоторых местах привел примеры, как стоит изменить код. 

Некоторые компоненты уже есть и их можно использовать для реализации формы (например `components/Form/Input`). 

Дополнительно расписал ниже:

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/@password/page.tsx
> +  }
В `react-hook-form` есть возможность подписываться на изменения других полей, и в режиме реального времени валидировать. Вот [небольшой пример](https://stackoverflow.com/a/70481425/8496835) того, как это работает. 

Не понятно, зачем в форму добавлять `setValue('change', response.change)`. Это действие добавит новое поле в form state, и в следующий раз при нажатии на кнопку отправит лишние поля. Уже есть `setSaved` можно в коде проверять если `{saved ? <>something</> : null}`. Если нужно проверить есть ли ошибка в запросе, можно добавить `setError(true)`.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/@password/page.tsx
> +  const [pass, setPass] = useState<string | null>()
Посмотри предыдущий комментарий. Можно по другому добавить сообщения об ошибке для поля пароля.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/@password/page.tsx
> +          />
Уже есть компонент для поля `input`, который содержит все необходимые стили:
```tsx
import {Input} from 'components/Form';

// jsx
...
<Input ... />
```

Возможно, чтобы передать ref в компонент Input, его нужно будет изменить (использовать ForwardRefRenderFunction). Можно посмотреть, как используется ForwardRefRenderFunction в Section или CheckBox. Дополнительно посмотри про [Controller](https://react-hook-form.com/api/usecontroller/controller/) - он тут пригодится.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/@profile/page.tsx
> +  }, [])
Обрати внимание, что для [`formState`](https://react-hook-form.com/api/useform/formstate/) можно указать источник данных (api endpoint):

```tsx
const { 
  formState: { isLoading } 
} = useForm({ 
  defaultValues: async () => await fetch('/api') 
});
```

Нужно переделать получение данных для формы в этом компоненте, и в `@password/page.tsx`.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/@profile/page.tsx
> +          />
Уже написал в комментарии выше, точно так же нужно использовать `components/Form` компонент `Input`.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/page.module.scss
Стоит пересмотреть этот файл и перенести стили для `@profile` и `@password` в эти папки (чтобы стили для компонентов были в том же месте, что и сами компоненты. Лишние стили, если есть, лучше всего убрать.

2023-04-19 10:18 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/page.tsx
Этот файл больше не нужен, его можно удалить. Он не содержит в себе никакой логики.

2023-04-19 18:16 UTC, NikolayN-ru commented on frontend/app/(main)/profile/layout.tsx
> +const Profile: (props: ProfileProps) => Promise<JSX.Element> = async ({ children }) => {
прошлый код выдавал ошибку типа / работает только с таким типом
-=-=-=-=-=-=-=-=-=-
Тип "({ children }: ProfileProps) => Promise<Element>" не может быть назначен для типа "FC<ProfileProps>".
  В типе "Promise<Element>" отсутствуют следующие свойства из типа "ReactElement<any, any>": type, props, keyts(2322)

2023-04-19 18:22 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +const Profile: (props: ProfileProps) => Promise<JSX.Element> = async ({ children }) => {
Скорее всего это из-за async. В файле нет асинхронного кода. Думаю, можно вернуть так как было.

2023-04-19 18:39 UTC, NikolayN-ru commented on frontend/app/(main)/profile/settings/page.module.scss
там одни и те же стили будут в разнах файлах для @profile и @password | норм ?

2023-04-21 17:49 UTC, paqstd-dev approved these changes

2023-04-21 17:49 UTC, merged