Frontend | News Single Page
DJWOMS/GSpot pull request #151
Opened 2023-04-20 18:33 UTC by matthewTheWizzard

Сделана основная верстка страницы News Single Page aka article.html

- [x] Созданы компоненты ArticleContent, Comments, RandomGame, RelatedNews, SocialLink, Subscribe
- [x] Добавлен дополнительный endpoint mocks/games/random 

TODO: продумать как будет добавляться контент на Article компонент

2023-04-21 20:38 UTC, paqstd-dev reviewed
Несколько замечаний по реализации:
- Контент необходимо загружать из моков. Должна быть загрузка на сервере (ssr);
- Комментарии необходимо загружать из моков (загрузка на клиенте только если пользователь долистал до раздела с комментариями);
- Новости необходимо загружать из моков (аналогично с комментариями, загружаем только если пользователь долистал до этого раздела);
- Происходит дублирование данных в RandomGame, RandomGameList и интерфейсах, которые связанны с ними. Необходимо использовать ListGames компонент.
- Необходимо все стили перенести на tailwind.

2023-04-24 19:00 UTC, matthewTheWizzard commented
> * Контент загружаутся из моков 
> * Комментарии загружаются из моков (Пока что без lazyload)
> * Убрал дублирование Random Game, поставил ListGame
> * Перенесено на TAILWIND

2023-04-25 12:44 UTC, paqstd-dev requested changes
Во многих местах используешь квадратные скобки для стилей. Лучше использовать встроенные значения. Если не подходит встроенный класс (или его нет) и кастомное значение встречается часто, его можно указать в `tailwind.config.js` файле. 

Заметил еще, комментарии ты пока загружаешь сразу при рендере страницы, ок. Можем это выделить в отдельную задачу позже. 

Обрати внимание, в шаблоне используются для разных элементов `border`, которого почему-то у тебя нет:
- Вот как в шаблоне: <img width="1332" alt="Снимок экрана 2023-04-25 в 15 41 31" src="https://user-images.githubusercontent.com/26341266/234279453-b3d7c268-e65d-46f8-ba4a-20a0edaab80b.png">
- Как у тебя: <img width="1317" alt="Снимок экрана 2023-04-25 в 15 40 52" src="https://user-images.githubusercontent.com/26341266/234279709-e49a2f32-d4b9-4774-a3d1-6c5e054d84c1.png">

В целом все хорошо. Указал еще некоторые комментарии, которые надо исправить:

2023-04-25 12:44 UTC, paqstd-dev commented on frontend/app/(main)/news/[id]/page.module.scss
> +}
Посмотри про [tailwind grid](https://tailwindcss.com/docs/grid-template-columns). Лучше не делать стили с процентами.

2023-04-25 12:44 UTC, paqstd-dev commented on frontend/app/(main)/news/[id]/page.tsx
> +
В next [можно получать id](https://beta.nextjs.org/docs/api-reference/file-conventions/page#props) из запроса. Нужно это использовать. Точно также и mocks сервер.

2023-04-25 12:44 UTC, paqstd-dev commented on frontend/app/(main)/news/[id]/page.tsx
> +              {articleContent && <ArticleContent>{articleContent}</ArticleContent>}
Такой проверки быть не может. Если запрос с ошибкой, например 404 [показываем ошибку сразу](https://beta.nextjs.org/docs/api-reference/notfound).

2023-04-25 12:44 UTC, paqstd-dev commented on frontend/features/news/components/Comments/SingleComment.tsx
> +import { IconMessageForward } from '@tabler/icons-react'
Такие импорты лучше объединять в один:
```tsx
import { IconThumbUp, IconThumbDown, ... } from '@tabler/icons-react'
```

2023-04-25 12:44 UTC, paqstd-dev commented on frontend/tailwind.config.js
> +    },
В tailwind есть [встроенные классы](https://tailwindcss.com/docs/responsive-design) для разных размеров экранов. Почему решил использовать кастомные значения?

2023-04-30 14:22 UTC, matthewTheWizzard commented on frontend/features/news/components/Comments/SingleComment.tsx
> +import { IconMessageForward } from '@tabler/icons-react'
done

2023-04-30 14:22 UTC, matthewTheWizzard commented on frontend/tailwind.config.js
> +    },
done

2023-04-30 14:23 UTC, matthewTheWizzard commented on frontend/features/news/components/ArticleContent/ArticleContent.tsx
> +// import Image from 'next/image'
done

2023-05-01 08:04 UTC, matthewTheWizzard commented on frontend/app/(main)/news/[id]/page.module.scss
> +}
done

2023-05-01 08:36 UTC, matthewTheWizzard commented on frontend/app/(main)/news/[id]/page.tsx
> +
done

2023-05-01 08:55 UTC, paqstd-dev approved these changes

2023-05-01 09:00 UTC, merged