Users | JWT Adapter, Developer Registration Diagram
DJWOMS/GSpot pull request #176
Opened 2023-04-27 20:04 UTC by oxpaoff

2023-04-29 03:32 UTC, mozambique-ya requested changes

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +		self.role = role
во первых: пробелов нет после двоеточий
второе: твой класс должен выполнять свою конкретную работу, а именно работать с jwt. Тут получается ты передаешь еще юзера, и потом формируешь payload на основе этого юзера. Так вот, у нас 3 типа юзеров, и у каждого может формироваться свой payload, и при твоей реализации это большая проблема становится.

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +	def generate_access_token(self) -> str:
можно же просто в метод добавить какой-нибудь параметр `data: dict`, в котором будут передаваться доп инфа, которую мы хотим зашить в тело токена

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +			"permissions":get_user_permissions(self.user)
а здесь соответственно будет **data.
И никакой сильной связанности с моделями джанги

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +		raise NotImplementedError()
реализацию работы с редисом делает другой человек, и его реализацию работы с редис с твоей реализацией работы с jwt соединим уже в services, где будет описываться логика.

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +			raise TokenExpired(f"Token Expired {now-exp} ago.")
было бы классно иметь еще один метод, который бы доставал оставшееся время жизни без exception (то что в телеге написал на твой вопрос)
а, так, да, для валидации надо кидать ошибку

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/.env.example
> +DEFAULT_AUTHENTICATION_CLASSES='rest_framework_simplejwt.authentication.JWTAuthentication, rest_framework.authentication.SessionAuthentication'
у нас же будет свой DEFAULT_AUTHENTICATION_CLASSES

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +		return 'Token Valid'
не, тут уж если возвращаешь что-то, то логичнее bool. 
хотя если что-то не так - то у тебя все равно ошибка выскочет, так что если вызвали этот метод, и он не вызвал никаких ошибок, значит токен норм

2023-04-29 03:32 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/adapter.py
> +		self.check_exp(token)
а проверка подписи?

2023-04-29 08:18 UTC, oxpaoff commented on backend/users/.env.example
> +DEFAULT_AUTHENTICATION_CLASSES='rest_framework_simplejwt.authentication.JWTAuthentication, rest_framework.authentication.SessionAuthentication'
Я просто перенес те классы что были в настройках, когда все переносил в .env

2023-04-29 08:19 UTC, oxpaoff commented on backend/users/backend/common/services/jwt/adapter.py
> +		raise NotImplementedError()
Понял, уберу тогда эти методы

2023-04-29 08:25 UTC, oxpaoff commented on backend/users/backend/common/services/jwt/adapter.py
> +	def generate_access_token(self) -> str:
доп инфа же будет только access токена?

2023-04-29 08:46 UTC, oxpaoff commented on backend/users/backend/common/services/jwt/adapter.py
> +		self.check_exp(token)
Декодирование токена можно считать за проверку токена?

2023-04-29 08:46 UTC, oxpaoff commented on backend/users/backend/common/services/jwt/adapter.py
> +		self.check_exp(token)
Так как если подпись не валидна, то токен не получится расшифровать

2023-04-29 13:35 UTC, mozambique-ya requested changes

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/token.py
>  		exp = iat + settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"]
от simpleJWT отказались же ) давай чтобы не вводить путаницу переименуем и конфиг сам

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/config/settings/simple_jwt.py
> +GET_TOKEN_FROM = os.environ["GET_TOKEN_FROM"]
хотелось бы понимать какие могут быть варианты. Добавь мб какой-нибудь Guard Clause для проверки. И если значение из окружения не совпадает с теми, которые могут быть - ставь значение по умолчанию с выводом warning. Это как вариант )

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/config/settings/simple_jwt.py
>  REFRESH_TOKEN_LIFETIME = json.loads(os.environ["REFRESH_TOKEN_LIFETIME"])
давай тут просто int в секундах принимать из переменных окружения. А то тоже надо описать значения какие могут быть

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/token.py
> +			"permissions":get_user_permissions(self.user),
это все должно приходить в твоем additional_data
то что мы будем собирать в additional_data - мы будем решать на этапе бизнес логики.
к примеру вчера выяснилось, что в тело токена нам надо засунуть аватарку пользователя и его ник. В твоей реализации придется править тут, когда как решение что добавить, а что убрать - другая задача. Задача твоего класса - сформировывать и проверять токены.

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/token.py
> +	def generate_access_token(self, additional_data: dict = {}) -> str:
в authentication у тебя обязательны поля user_id и role.
Добавь их как обязательные параметры.
либо можно сделать другим способом: для класса реализовать свойство c перечислением обязательных ключей, которые должны быть в additional_data, и далее при генерации токена проверять наличие этих ключей в словаре additional_data. Может придумаешь еще способ )

2023-04-29 13:35 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/token.py
> +		self.role = user._meta.app_label
убирай работу с User вообще из класса. Вспоминаем принцип единой ответственности - твой класс только выдает и проверяет токены

2023-04-29 15:33 UTC, oxpaoff commented on backend/users/backend/config/settings/simple_jwt.py
> +GET_TOKEN_FROM = os.environ["GET_TOKEN_FROM"]
Для GET_TOKEN_FROM?

2023-05-01 08:43 UTC, mozambique-ya approved these changes

2023-05-01 08:43 UTC, merged