Users | add redis in project
DJWOMS/GSpot pull request #178
Opened 2023-04-28 05:21 UTC by Edgar-84

2023-04-28 07:07 UTC, mozambique-ya requested changes

2023-04-28 07:07 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
> +        pass
класс не доработан в соответствии с требованиями:
- проверка access токена (при верификации от других сервисов) и его добавление
- наличие refresh токена в черном списке и его добавление
- хранение totp и его добавление - это пока не проговаривали, но скорее всего так будет

у нас общая область использования redis всеми сервисами - это проверка access токена (я узнаю какую структуру данных они выбрали для этого).
Для refresh и totp выбери сам, что лучше использовать

2023-04-29 03:02 UTC, mozambique-ya requested changes

2023-04-29 03:02 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
> +                                               db=redis_config.REDIS_DB,
у тебя в конфиге REDIS_ACCESS_DB и REDIS_REFRESH_DB, а здесь REDIS_DB

2023-04-29 03:02 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
> +    def add_token_in_black_list(self, token: str, ttl: float):
add_token_in_black_list - скорее уж add_token_to_black_list

2023-04-30 08:42 UTC, mozambique-ya requested changes
1) реализация redis_client - почти ок, но есть вопрос: что если refresh и access токены могут хранится во вложенном ключе?
да, мы можем положить токен с ключом таким же как и сам токен. Но можем положить и с "префиксом", т.е. типа blacklist::<token>
2) надо доделать методы в RedisValidateToken
3) можно сразу проинициализировать RedisValidateToken для двух видов токенов, чтобы твоим коллегам было проще )

2023-04-30 08:42 UTC, mozambique-ya commented on backend/users/backend/utils/redis_client.py
> +
ну и сразу можно создать эти 2 клиента
redis_access_client = RedisAccessClient()
и для refresh

2023-04-30 08:42 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
>  class RedisValidateToken:
класс должен работать с клиентом, который ты создал в redis_client
хотя вижу что ты передаешь клиента в методах

2023-04-30 08:42 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
> +    def is_access_token_exist(self, client: RedisClient, token: str) -> bool:
метод переименовать, т.к. он будет работать как с access токеном, так и с refresh.
ну и сама реализация метода тоже нужна

2023-04-30 08:42 UTC, mozambique-ya commented on backend/users/backend/utils/redis.py
> +    def add_valid_token(self, client: RedisClient, token: str, ttl: int) -> None:
метод переименовать, т.к. он будет работать как с access токеном, так и с refresh. Если с access, то да, он valid. А если refresh мы добавляем в чс, то он уже по смыслу не vlid
ну и сама реализация метода тоже нужна

2023-05-09 07:39 UTC, mozambique-ya requested changes
Отлично! Но немножко причешем еще:
1) redis_client.py и redis_validate.py убери в utils/db (или как-нибудь сам назови) - будет удобнее навигация, если в одном модуле эти 2 файла, то сразу можно понять, что они связаны. В utils будут модули и по rabbitMQ и по обогащению данных из payments - опять же, чтобы не путаться, все будет на своих полочках лежать )
2) тестики :)

2023-06-06 12:21 UTC, gravity48 commented on backend/users/.env.example
> +REDIS_HOST = 0.0.0.0
Хосты редис сразу прописываем в .env.tests по доменному имени, не забываем посмотреть что тесты работают

2023-06-06 12:22 UTC, gravity48 commented on backend/users/backend/utils/db/redis_client.py
> +        return self.__redis_client
У базового класса должны быть методы get (получить данные из redis) и put(положить данные в redis) в дальнейшем ты их будешь использовать в дочерних классах

2023-06-06 12:26 UTC, gravity48 commented on backend/users/docker/docker-compose.local.yml
> +      - ../.env
Используем .env.tests

2023-06-06 12:27 UTC, gravity48 commented on backend/users/docker/docker-compose.local.yml
> +
Неисключено что придется добавить healthcheck чтобы тесты корректно отработали на CI/CD

2023-06-12 13:17 UTC, gravity48 requested changes

2023-06-12 13:17 UTC, gravity48 commented on backend/users/backend/utils/db/redis_client.py
> +        self.put(name=key, value=token, ttl=ttl)
Ты добавил метод add_token все верно. Но почему метод is_token_exist не учитывает prefix?

2023-06-12 13:17 UTC, gravity48 commented on backend/users/backend/utils/db/redis_client.py
> +        if self.get(token):
В add_token ты учитывешь prefix, но почему то не учитываешь его в методе is_token_exist?
Это значительно упростило использования кода другими программистами.

2023-06-12 13:17 UTC, gravity48 commented on backend/users/backend/utils/db/redis_client.py
> +        self.put(name=key, value=token, ttl=ttl)
Давай предусмотрим что value это не просто токен, а словарь, в котором могут дополнительно храниться какие то данные

2023-06-14 11:51 UTC, gravity48 requested changes

2023-06-14 11:51 UTC, gravity48 commented on backend/users/backend/config/settings/redis_config.py
> +REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', 'Qwe123!@#')
Давай предусмотрим что пароля может и не быть, здесь вернем None, если в .env такого нет

2023-06-14 11:51 UTC, gravity48 commented on backend/users/docker-compose.tests.yml
> +    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
Давай добавим еще эту команду в override.yml

2023-06-15 02:28 UTC, mozambique-ya approved these changes

2023-06-15 05:55 UTC, gravity48 approved these changes

2023-06-15 05:55 UTC, merged