Frontend|Pagination
DJWOMS/GSpot pull request #186
Opened 2023-04-29 18:31 UTC by Raphael163

2023-05-01 07:10 UTC, paqstd-dev requested changes
`Pagination` компонент должен вызывать внутри себя колбэк (callback) `onPaginate`:
```tsx
<Pagination onPaginate={(page) => console.log(page)} />
```
Поскольку компонент изолирован, передается внутрь колбэк. При изменении страницы внутри компонента `Paginate` вызывается функция `onPaginate`. Можно рассмотреть и другие названия колбэк функции, например onPageChange, onChange и тд. 

Рассмотри вариант использования [react-paginate](https://www.npmjs.com/package/react-paginate). Если нет необходимости использовать эту библиотеку, необходимо добавить еще скрытие части кнопок перехода на определенную страницу. Показываем только те кнопки, которые находятся рядом с текущей цифрой страницы: 
<img width="548" alt="Снимок экрана 2023-05-01 в 10 04 16" src="https://user-images.githubusercontent.com/26341266/235420382-f6cd209b-75ad-4942-9a8e-b9a18850b3bd.png">

2023-05-02 18:24 UTC, paqstd-dev submitted a review, later dismissed
По шаблону есть еще слева блок с количеством элементов: 
<img width="1061" alt="Снимок экрана 2023-05-02 в 21 21 33" src="https://user-images.githubusercontent.com/26341266/235752100-24b3541e-0b64-43fb-bf83-c7d8d4ed38c2.png">

У тебя выглядит вот так (его нет):
<img width="1373" alt="Снимок экрана 2023-05-02 в 21 14 44" src="https://user-images.githubusercontent.com/26341266/235751820-ac515ded-d830-4327-a7e8-6e6fdddfa1d7.png">

Все таки давай сделаем как по шаблону. Слева показываем количество элементов на текущей странице + общее количество элементов. Еще сам блок с пагинацией сейчас слишком большой, хотелось бы получить так как в шаблоне (немного больше будет, но слева).

2023-05-02 18:24 UTC, paqstd-dev commented on frontend/components/Pagination/Pagination.tsx
>  const Pagination = () => {
Компонент должен принимать функцию колбек, вызывая ее в `onPageChange`.

2023-05-02 18:24 UTC, paqstd-dev commented on frontend/components/Pagination/Pagination.tsx
> +      pageCount={100}
Количество страниц передается в props этого компонента.

2023-05-07 15:04 UTC, kieled approved these changes

2023-05-07 15:07 UTC, merged