Frontend | Features/loading
DJWOMS/GSpot pull request #196
Opened 2023-05-02 14:03 UTC by KarolinaEsepenok

Есть пару вопросов, которые хотелось бы обсудить:
1. В файлs loading.tsx стоит ли переносить <Section/> с тайтлом, чтобы отображались сразу названия блоков или вместо этого написать Loading? или не нужен этот блок?(но без него там верска "сбивается").
2. Нужен ли скелетон на стр каталог на фильтрах? он там реализован, но зависит от загрузки games. Тот что я реализовала, просто накладывается наверх, Мне кажется будет лучше убрать тот, который я реализовала и оставить тот, который был(я не знаю как его спрятать при адаптиве, там фильтры сворачиваются на определенной ширине).
3. У меня проблема с версткой адаптивной части, так как не всегда корректно отображается адаптив самих страниц(медленная загрузка).
4. Скелетон на стр новости использовала тот, что для карточки игры, он очень похож на дизайн новости, но отличия в длине картинки, есть ли смысл создавать компонент на скелетон новости? я просто не смогла задать другую длину, может и так можно.
очень жду комментарии)

2023-05-02 19:04 UTC, paqstd-dev requested changes
Loading ui должен быть максимально "обезличен" - не имеет никаких названий, все блоки повторяют примерный интерфейс страницы или блока. Текстовые названия или блоки можно делать линиями разных размеров. 

Импорт всех компонентов Skeleton должен быть примерно таким:
```tsx
import {SkeletonCard} from 'components/Skeleton'
```
Для этого нужно в файле `components/Skeleton/index.ts` указать импорты из `components/Skeleton/*/**`. 

Перед созданием коммита важно проверить изменения (опечатки, лишние комментарии и отступы). 

Необходимо подтянуть последние изменения frontend ветки и добавить loading файлы для news details страницы.

2023-05-02 19:04 UTC, paqstd-dev commented on frontend/app/(main)/catalog/loading.tsx
> +              <Pagination />
Нельзя использовать интерактивные компоненты для loading ui, такие как Paginaton, Carousel и тд. Такие компоненты могут делать запросы в api, делать некоторые вычисления и тд. 

Loading ui обычно должен содержать стили для блоков и сами блоки. Никакой сложной js/ts логики не хранит.

2023-05-03 08:55 UTC, KarolinaEsepenok commented on frontend/app/(main)/catalog/loading.tsx
> +              ))}
нужен ли этот второй скелетон на фильтры? я спрашивала в первом комментарии. и как реализовать, чтобы для моб устройств он спрятался, если в файле лоадинг нет логики? создать компонент скелетон на фильтры отдельный?

2023-05-03 08:57 UTC, KarolinaEsepenok commented on frontend/app/(main)/catalog/loading.tsx
> +              <Pagination />
Тогда можно создавать стили для лоадинг в разметке или можно для него отдельный файл со стилями? в интернете встречала стили в разметке лоадинг.

2023-05-03 09:20 UTC, KarolinaEsepenok commented on frontend/app/(main)/loading.tsx
> +}
Лучше на название блока сделать отдельный скелетон тогда?

2023-05-04 11:20 UTC, paqstd-dev commented on frontend/app/(main)/loading.tsx
> +}
Название можно сделать линией

2023-05-04 11:22 UTC, paqstd-dev commented on frontend/app/(main)/page.module.scss
> +}
Для каждого компонента скелетона стили хранятся рядом с этим компонентом

2023-05-04 11:24 UTC, paqstd-dev commented on frontend/app/(main)/catalog/loading.tsx
> +              ))}
Прятать можно через стили. В tailwind есть [классы](https://tailwindcss.com/docs/responsive-design) для работы с разными размерами.

2023-05-04 11:26 UTC, paqstd-dev commented on frontend/app/(main)/catalog/loading.tsx
> +              <Pagination />
В идеале, конечно, делать отдельно. Можно попробовать сделать к примеру loading.module.scss файл для таких стилей

2023-05-08 14:12 UTC, kieled approved these changes

2023-05-08 14:12 UTC, merged