Users | logout
DJWOMS/GSpot pull request #227
Opened 2023-05-11 18:25 UTC by oxpaoff

2023-05-12 06:44 UTC, mozambique-ya requested changes
Оч хорошо!
написал коммент под вьюсетом + нужны тесты )

2023-05-12 06:44 UTC, mozambique-ya commented on backend/users/backend/common/services/jwt/blacklist.py
> +        raise NotImplementedError
по сути реализация добавления в чс - у другого человека. Как заглушка в данном случае - ок ) но потом от этого избавимся )

2023-05-12 06:44 UTC, mozambique-ya commented on backend/users/backend/common/views/v1/logout_view.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
с фронтом мы не говорили еще, конечно, но я буду настаивать на том, чтобы передавать рефреш токен в посте (они я так понял сами не понимают как куки настраиваются в браузере), т.к. это будет гарантировать, что токен придет к нам на бекенд. Поэтому давай сразу под пост и сделаем )

2023-05-12 06:52 UTC, oxpaoff commented on backend/users/backend/common/views/v1/logout_view.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
уже под пост сделано

2023-05-14 07:26 UTC, mozambique-ya approved these changes

2023-05-14 07:26 UTC, merged