Endpoint save to LIbrary
DJWOMS/GSpot pull request #250
Opened 2023-05-18 10:02 UTC by BogdanVol

2023-05-18 21:58 UTC, JustLike420 commented on backend/games/core/urls.py
> +    path('save_to_library', save_to_library, name='save_to_library'),
слеш в конце

2023-05-18 21:58 UTC, JustLike420 commented on backend/games/core/views.py
> +def save_to_library(request):
Это же я просто привел пример логики, которую на мите писал. 
Просто тупо ctrl+c ctrl+v

2023-05-30 10:14 UTC, JustLike420 commented on backend/games/core/views.py
> +        return Response({'message': 'Games added to library successfully'})
статус не указан

2023-05-30 10:14 UTC, JustLike420 commented on backend/games/core/serializers.py
> +    user_to = serializers.UUIDField()
добавить user_from

2023-05-30 10:14 UTC, JustLike420 commented on backend/games/core/views.py
> +    def get_or_create_library(self, user_to):
https://docs.djangoproject.com/en/4.2/ref/models/querysets/#get-or-create

в джанге уже есть такой метод

2023-05-30 10:14 UTC, JustLike420 commented on backend/games/core/views.py
> +    def get_active_offer(self, offer_uuid):
в джанге есть уже такой функционал использовать Offer.objects.filter(...).first()
вернет или offer, или None

2023-05-30 10:14 UTC, JustLike420 commented on backend/games/core/views.py
> +            return Offer.objects.get(created_by=offer_uuid, is_active=True)
почему created_by=offer_uuid, ведь created_by - разработчик, который создал предложение

2023-05-30 10:20 UTC, JustLike420 commented
и еще flake8 не прошел.
у тебя стоит пре комит?

2023-06-12 11:23 UTC, JustLike420 requested changes

2023-06-12 11:23 UTC, JustLike420 commented on backend/games/core/views.py
> +    def post(self, request):
ты поменял get на post, но далее data=request.GET. Ты тестировал работоспособность?

2023-06-12 11:23 UTC, JustLike420 commented on backend/games/core/views.py
> +        library, _ = Library.objects.get_or_create(user=user_to)
а зачем делать отдельно в функции? помести туда, где вызывается функция get_or_create_library

2023-06-12 11:23 UTC, JustLike420 commented on backend/games/core/views.py
> +        offer = get_object_or_404(Offer, id=offer_uuid)
а зачем делать отдельно в функции? помести туда, где вызывается функция get_active_offer

2023-06-13 12:58 UTC, JustLike420 requested changes

2023-06-13 12:58 UTC, JustLike420 commented on backend/games/core/data.json
не в виде файла, а как комментарий к ПР

2023-06-13 12:58 UTC, JustLike420 commented on backend/games/core/views.py
> +from rest_framework.views import APIView
2 раза APIview, Flake на этом выдает ошибку

2023-06-13 16:29 UTC, JustLike420 requested changes

2023-06-13 16:29 UTC, JustLike420 commented on backend/games/core/views.py
> +        serializer = SaveToLibrarySerializer(data=request.GET)
data=request.GET тут еще

2023-06-13 16:33 UTC, BogdanVol commented
[data.tar.gz](https://github.com/DJWOMS/GSpot/files/11737142/data.tar.gz)

2023-06-13 16:50 UTC, BogdanVol commented
{
    "userTo": [
      "Обязательное поле."
    ],
    "offerUuid": [
      "Обязательное поле."
    ]
 }

2023-06-21 12:30 UTC, JustLike420 approved these changes

2023-06-21 12:31 UTC, merged