Users docker refactoring
DJWOMS/GSpot pull request #261
Opened 2023-05-23 07:37 UTC by oxpaoff

2023-05-23 08:59 UTC, mozambique-ya requested changes
1) вынеси все компоузы в наш рут, т.е. в backend/users + добавь docker-compose.tests.yml и .env файлы под каждый компоуз. Для local и tests переменные должны быть определены, чтобы не заполнять их вручную, а сразу запустить все
2) Dockerfile и .sh скрипты перенеси в backend/users/docker
3) по переменным DJANGO_SUPERUSER_USERNAME я понял - лучше описать в инструкции когда развернули приложение, что надо создать суперюзера (+ пример, делается через контейнер)
4) инструкции

2023-05-23 08:59 UTC, mozambique-ya commented on backend/users/.env.example
> +DJANGO_SUPERUSER_PHONE=123123123
а зачем нам это?

2023-05-23 08:59 UTC, mozambique-ya commented on backend/users/.env.example
> +DB_PORT=5432
мб для красоты назвать их как POSTGRES_HOST и POSTGRES_PORT?

2023-05-23 08:59 UTC, mozambique-ya commented on backend/users/backend/common/tests/test_logout.py
на будущее давай разграничивать pr, вроде pr про докер, а тут тесты...

2023-05-23 08:59 UTC, mozambique-ya commented on backend/users/backend/config/settings/auth.py
> +DJANGO_SUPERUSER_EMAIL = os.environ["DJANGO_SUPERUSER_EMAIL"]
пока не понял зачем это )

2023-05-23 08:59 UTC, mozambique-ya commented on backend/users/docker/docker-compose.yml
здесь давай запуск только web_users - т.е. чисто само приложение для продакшена. Postgres, Redis, RabbitMQ скорее всего будут сторонние
переменные окружения определи как prod.env, например.

+ вынеси в backend/users/docker-compose.yml

2023-05-26 17:48 UTC, oxpaoff commented on backend/users/backend/common/tests/test_logout.py
это вроде из-за того, что предыдущий pr с тестами не был принят эти изменения отобразились тут. а так конечно понимаю что не надо мешать изменения

2023-05-27 13:44 UTC, oxpaoff commented on backend/users/backend/config/settings/auth.py
> +DJANGO_SUPERUSER_EMAIL = os.environ["DJANGO_SUPERUSER_EMAIL"]
это для создания суперпользователя без ввода данных

2023-05-28 19:37 UTC, mozambique-ya requested changes
1) в docker-compose.local.yml и docker-compose.tests.yml не хватает redis
2) вижу Dockerfile.test - он нам не нужен
3) остальное в комментах отписал
4) в инструкции я добавил бы пункт, что надо создать .env файл для запуска docker-compose.yml (на основе примерочного)
5) DJANGO_ENV - какие может принимать значения?
6) DJANGO_LOG_LEVEL - какие может принимать значения?
7) DJANGO_CORS_ALLOWED_ORIGINS - где у нас используется?
8) в DJANGO_ALLOWED_HOSTS что нужно писать?

2023-05-28 19:37 UTC, mozambique-ya commented on backend/users/.env.local
подразумевается, что этот файл не надо трогать для локальной разработки, т.е. взяли ввели команду docker-compose -f docker-compose.local.yml up -d, и локально запустили в своей ide python manage.py runserver, и спокойно пишем код
и тут у тебя POSTGRES_HOST=db - это хост внутри контейнеров, и это правильно, но с локальной машины у тебя не будет доступа к db
также и для RABBITMQ_HOST

2023-05-28 19:37 UTC, mozambique-ya commented on backend/users/README.md
> +**NOTE**: docker-compose.local.yml - for project's db (Postgres, Redis, Rabbitmq)
лучше написать, что этот компоуз для development

2023-05-28 19:37 UTC, mozambique-ya commented on backend/users/README.md
> +$ docker-compose -f docker-compose.yml \
вряд ли кто-то из нас разрабатывает внутри контейнера. Гораздо удобнее локально это делать. Поэтому docker-compose.yml тут не нужен

2023-05-28 19:37 UTC, mozambique-ya commented on backend/users/README.md
> +                 -f docker-compose.local.yml \
docker-compose.tests.yml уже содержит все из docker-compose.local.yml, поэтому docker-compose.local.yml тут не нужен

2023-06-03 08:56 UTC, gravity48 approved these changes

2023-06-03 09:28 UTC, gravity48 approved these changes

2023-06-03 09:30 UTC, mozambique-ya approved these changes

2023-06-03 09:30 UTC, merged