Users | Authentication for Admin|Developer|Customer
DJWOMS/GSpot pull request #273
Opened 2023-05-27 20:32 UTC by balabiturembekov

2023-05-28 09:52 UTC, mozambique-ya requested changes
привет!
Прям зачет тебе за описание к PR ) 
В целом очень хорошо! Есть моменты которые надо поправить:
1) нет swagger описания
2) по 2ому пункту твоего описания к PR permissions_codename - если хочешь такой подход использовать, то  надо дописать методы. Не забывай, что у админа есть свои пермишены, и есть еще пермишены разработчика. Так же есть группы пермишенов, которые надо учитывать тоже.

2023-05-28 09:52 UTC, mozambique-ya commented on backend/users/backend/base/models.py
> +        return list(self.user_permissions.values_list("codename", flat=True))
у тебя там self.user_permissions, но в этом базовом классе ничего не известно про user_permissions.

2023-05-28 09:52 UTC, mozambique-ya commented on backend/users/backend/customer/views/v1/auth_view.py
> +class CustomerAuthView(APIView):
swagger описание?

2023-05-28 09:52 UTC, mozambique-ya commented on backend/users/backend/customer/views/v1/auth_view.py
> +            "avatar": str(customer.avatar),
про аватар уже писал выше

2023-05-28 09:52 UTC, mozambique-ya commented on backend/users/backend/developer/views/v1/auth_view.py
> +class DeveloperAuthView(APIView):
swagger описание?

2023-05-28 09:52 UTC, mozambique-ya commented on backend/users/backend/developer/views/v1/auth_view.py
> +            "avatar": str(developer.avatar),
про аватар писал выше

2023-05-28 17:23 UTC, balabiturembekov commented on backend/users/backend/administrator/views/v1/auth_view.py
> +            "avatar": str(admin.avatar),
Если значение не задано, то это пустая строка.

```python
print(str(customer.avatar))
```
Вывод пустая строка

2023-05-28 17:26 UTC, balabiturembekov commented on backend/users/backend/administrator/views/v1/auth_view.py
> +class AdminAuthView(APIView):
Я хотел сделать описания swagger, но почему-то подумал что Илья будет это делать и не стал. Sorry, исправлю.

2023-05-28 17:36 UTC, balabiturembekov commented on backend/users/backend/base/models.py
> +        return list(self.user_permissions.values_list("codename", flat=True))
Я что-то тупанул с этим `permissions_codename`.
Может реализовать это свойство отдельно в каждой модели?

Для `Admin` будет так:
```python
@property
def permissions_codename (self) -> list[str]:
    return list(self.user_permissions.values_list("codename", flat=True) + list(self.developer_permissions.values_list("codename", flat=True)
```
Для `Developer` будет так:
```python
def permissions_codename(self) -> list[str]:
    return list(self.user_permissions.values_list("codename ", flat=True))

2023-05-28 17:36 UTC, balabiturembekov commented on backend/users/backend/base/models.py
> +        return list(self.user_permissions.values_list("codename", flat=True))
Я что-то тупанул с этим `permissions_codename`.
Может реализовать это свойство отдельно в каждой модели?

Для `Admin` будет так:
```python
@property
def permissions_codename (self) -> list[str]:
    return list(self.user_permissions.values_list("codename", flat=True) + list(self.developer_permissions.values_list("codename", flat=True)
```
Для `Developer` будет так:
```python
def permissions_codename(self) -> list[str]:
    return list(self.user_permissions.values_list("codename ", flat=True))

2023-05-28 19:42 UTC, mozambique-ya commented on backend/users/backend/administrator/views/v1/auth_view.py
> +            "avatar": str(admin.avatar),
точно?) в модели null=True ) avatar = models.ImageField(null=True, blank=True)

2023-05-28 19:43 UTC, mozambique-ya commented on backend/users/backend/administrator/views/v1/auth_view.py
> +class AdminAuthView(APIView):
Илья сделает описания к ручкам, которые были уже сделаны. В новых, т.е. которые сейчас в разработке, делаем уже сами

2023-05-28 19:43 UTC, mozambique-ya commented on backend/users/backend/base/models.py
> +        return list(self.user_permissions.values_list("codename", flat=True))
как вариант )

2023-05-28 19:45 UTC, balabiturembekov commented on backend/users/backend/administrator/views/v1/auth_view.py
> +class AdminAuthView(APIView):
Я только что сделал коммит с описанием Swagger

2023-05-28 19:48 UTC, balabiturembekov commented on backend/users/backend/administrator/views/v1/auth_view.py
> +            "avatar": str(admin.avatar),
Я принтанул значение и в логах dev сервера показывает что пусто

2023-05-29 05:33 UTC, mozambique-ya requested changes
не делай двойную работу с ручным описанием реквеста и респонса в сваггер описании. У тебя есть уже сериализатор на реквест, просто вставь его туда. Также и с респонсом - сделай общий сериализатор, и также используй его в описании и оборачивай в выходные данные

так как ты сделал - можно сделать. Но если у тебя не 2 поля, а 20 полей? долго описывать придется )

2023-05-29 05:33 UTC, mozambique-ya commented on backend/users/backend/administrator/views/v1/auth_view.py
> +        ),
у тебя же написан уже сериализатор AdminAuthSerializer, впихни его сюда ) и описывать вручную не придется )

2023-05-29 05:33 UTC, mozambique-ya commented on backend/users/backend/administrator/views/v1/auth_view.py
> +            ),
1) ты возвращаешь tokens, а надо access_token и refresh_token
2) сделай тоже сериализатор, типа так:
class AuthTokensResponse(serializers.Serializer):
    access_token
    refresh_token
и впихни его сюда
и в самой вьюшке оберни в этот сериализатор на выход, типа так:
serializer = AuthTokensResponse(data=tokens)
return Response(serializer.data)

2023-05-29 17:16 UTC, mozambique-ya approved these changes

2023-05-29 17:16 UTC, merged