Users | Added CRUD functionality for Country and Content Type models
DJWOMS/GSpot pull request #275
Opened 2023-05-29 15:54 UTC by Roman-Zhirovskis

2023-05-29 17:12 UTC, mozambique-ya requested changes
вьюшки хорошо описаны, зачет )

1) ты немного напутал в нейминге ) ContentType у нас нет, есть ContactType ) где-то ты правильно называешь, где-то нет ) поправь пожалуйста все согласно ContactType (названия фалов тоже)
2) не хватает пограничных случаев в тестах, например retrive не существующего id, добавление страны или типа контакта, которое уже есть в бд и т.д.
3) в тестах надо бы учесть, что в будущем мы повесим пермишены на определенные действия (например can_edit_country, can_remove_contacttype и т.д.). И у тебя пока сложно представить как добавить это все в тесты. Там получается надо создавать много юзеров с разными вариациями прав, и каждый случай практически индивидуально проверять

2023-05-29 17:12 UTC, mozambique-ya commented on backend/users/backend/common/tests/test_country.py
у тебя в MixinTestView 6 методов для тестов, и 2 юзера => 12 тестов должно быть )
а тут 7 )

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/tests/test_contenttype.py
> +    url: str = "/api/users/common/contact_types/"
Используй функцию reverse, поскольку путь к api может измениться

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/tests/test_country.py
> +    url: str = "/api/users/common/countries/"
Используем функцию reverse

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/views/v1/contenttype_view.py
> +            204: openapi.Response("Запись успешно удалена", ContactTypeSerializer),
destroy по умолчанию ничего не возвращает кроме статус кода

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/views/v1/countrylist_view.py
> +            201: openapi.Response(
update возвращает 200 ответ

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/views/v1/countrylist_view.py
> +            204: openapi.Response(
destroy возвращает только статус

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/views/v1/countrylist_view.py
> +            ),
Добавь ошибку 404

2023-05-30 07:52 UTC, gravity48 commented on backend/users/backend/common/views/v1/countrylist_view.py
> +            400: openapi.Response("Входные данные не валидны"),
400 ошибки при дестрое быть не может ты не передаешь ей никаких данных

2023-06-06 13:11 UTC, closed without merging