FRONTEND | Auth
DJWOMS/GSpot pull request #292
Opened 2023-06-06 17:39 UTC by matthewTheWizzard

Добавил проверку аутонтификации на стороне фронтенда

2023-06-08 18:36 UTC, kieled commented
Давай сделаем новую фичу `auth`. В неё нужно закинуть эти тестовые переменные `access_token` и `refresh_token`, а так же интерфейс `AuthPayload`. Функции для обработки на стороне сервера и клиета так же разместить в папке `utils` внутри фичи. Эксортировать наружу всё выше перечисленное по аналогии с другими фичами, за тем исключением что эти основноые две функции должны быть экспортированы на уровень фичи, т.е. чтобы их можно было импортировать так: 
```js
import { checkAuthClient, checkAuthServer } from 'feature/auth'
```

2023-06-08 18:43 UTC, kieled requested changes

2023-06-08 18:43 UTC, kieled commented on frontend/utils/checkAuthServer.ts
> +  }
нужно сделать функцию асинхронной и без `then`

2023-06-08 18:43 UTC, kieled commented on frontend/utils/checkAuthServer.ts
> +      method: 'POST',
на бэкенде этот урл не будет принимать body, он будет забирать куку. Тут нужно добавить куку к запросу в атрибут `cookie` в `headers`

2023-06-09 13:54 UTC, matthewTheWizzard commented on frontend/utils/checkAuthServer.ts
> +  }
готово

2023-06-09 13:54 UTC, matthewTheWizzard commented on frontend/utils/checkAuthServer.ts
> +      method: 'POST',
готово

2023-06-09 14:00 UTC, kieled requested changes

2023-06-09 14:18 UTC, kieled requested changes

2023-06-09 14:18 UTC, kieled commented on frontend/features/auth/utils/checkAuthServer.ts
> +      })
только сейчас заметил, что тут ведь запрос делается с сервера, значит куки вернуться на сервер, соответвенно нужно через `cookieStorage` засэтать их клиенту

2023-06-09 14:18 UTC, kieled commented on frontend/features/auth/utils/checkAuthClient.ts
> +const doesHttpOnlyCookieExist = (cookiename: string) => {
`cookieName` вместо `cookiename`

2023-06-09 14:18 UTC, kieled commented on frontend/features/auth/utils/index.ts
> +export * from './checkAuthServer'
у меня ещё появились сомнения на счет этого. Если мы допустим будем с клиента вызывать функцию `checkAuthClient` не потянется ли сюда импорт  `next/headers` и не упадёт ли ошибка.

2023-06-09 14:22 UTC, matthewTheWizzard commented on frontend/features/auth/utils/index.ts
> +export * from './checkAuthServer'
я проверял уже checkAuthClient в useEffect, все работало

2023-06-10 08:08 UTC, kieled approved these changes

2023-06-10 08:08 UTC, merged