Frontend | Replaced filter with a reusable form component
DJWOMS/GSpot pull request #298
Opened 2023-06-08 09:16 UTC by Raphael163

2023-06-09 08:31 UTC, kieled requested changes

2023-06-09 08:31 UTC, kieled commented on frontend/features/games/components/FilterGames/FilterGames.tsx
> +  const { setValue } = useForm<FilterValues>({
в этом компоненте больше не должно быть useForm

2023-06-09 08:31 UTC, kieled commented on frontend/features/games/components/FilterGames/FilterGames.tsx
> +const FilterGames = ({ sorts, platforms, genres, prices }: Props) => {
почему `FC<Props>` было заменено на такой вариант?

2023-06-09 08:31 UTC, kieled commented on frontend/features/games/components/FilterGames/FilterGames.tsx
> +          onResetSubmit
эти атрибуты лучше вынести перед fields чтобы не приходилось пролистывать весь компонент

2023-06-09 20:49 UTC, Raphael163 commented on frontend/features/games/components/FilterGames/FilterGames.tsx
> +  const { setValue } = useForm<FilterValues>({
Убрал

2023-06-09 20:50 UTC, Raphael163 commented on frontend/features/games/components/FilterGames/FilterGames.tsx
> +          onResetSubmit
Поправил

2023-06-10 08:05 UTC, kieled approved these changes

2023-06-10 08:05 UTC, merged