Users | token for user fix
DJWOMS/GSpot pull request #319
Opened 2023-06-17 10:12 UTC by oxpaoff

2023-06-17 12:22 UTC, gravity48 requested changes
Удали blacklist.py если он не нужен

2023-06-17 12:22 UTC, gravity48 commented on backend/users/backend/common/services/jwt/decorators.py
> +    return wrapper
Декораторы в данном случае не совсем то что нужно, мы не расширяем функционал а просто делаем проверки они должны быть видны и читаемы.

2023-06-17 12:22 UTC, gravity48 commented on backend/users/backend/common/services/jwt/token.py
>      def generate_refresh_token(self, data: dict) -> str:
Эти методы предлагаю сделать protected тогда и валидировать дополнительно их не придется, их по умолчанию не нужно будет использовать

2023-06-17 12:22 UTC, gravity48 commented on backend/users/backend/common/services/jwt/request.py
> +from base.exceptions import AuthenticationFailed
Ошибка в тестах была из за этого модуля, который лежит отдельно от аутентификации, давай функционал перенесем туда и настройку откуда брать токен он будет подхватывать там

2023-06-17 12:22 UTC, gravity48 commented on backend/users/backend/common/services/jwt/token.py
>          access_token = self.generate_access_token_for_user(user)
Здесь нужно написать что то вроде этого
assert user.is_banned is not True, 'Пользователь не должен быть забанен'

2023-06-18 20:21 UTC, oxpaoff commented on backend/users/backend/common/services/jwt/token.py
>      def generate_refresh_token(self, data: dict) -> str:
эти методы вроде можно будет и отдельно использовать, для генерации токенов отдельно

2023-06-19 08:19 UTC, gravity48 commented on backend/users/backend/common/services/totp/totp.py
> +            )
Не совсем смысл понял, я хочу чтобы функция вызывалась sel.message(message) без лишних подтягивания настроек. Нужно будет исправить data классы

2023-06-19 08:26 UTC, gravity48 requested changes

2023-06-19 08:26 UTC, gravity48 commented on backend/users/backend/common/services/jwt/authentication.py
> +        token = request.META.get('HTTP_AUTHORIZATION')
Этот метод делаем protected

2023-06-19 08:26 UTC, gravity48 commented on backend/users/backend/common/services/jwt/authentication.py
> +        token = request.COOKIES.get('Authentication')
Метод делаем protected

2023-06-19 15:44 UTC, gravity48 approved these changes

2023-06-19 15:44 UTC, merged