feat: add a function that handles errors from fetchServerSide
DJWOMS/GSpot pull request #326
Opened 2023-06-18 17:43 UTC by matthewTheWizzard

Добавил функцию которая отображает ошибки 401 и 400 на экран
Для отображения ошибки добавил зависимость react-hot-toast

2023-06-21 17:11 UTC, kieled approved these changes

2023-06-21 17:11 UTC, kieled commented on frontend/lib/errorHandler.ts
> +      return await fetchServerSide({ path: 'auth/refresh', method: 'POST' })
внутри `checkAuthClient` уже делается запрос на refresh, если это необходимо. А зачем в случае если пользователь авторизован ещё раз обновлять ему токен

2023-06-21 17:13 UTC, kieled requested changes

2023-06-21 17:13 UTC, kieled commented on frontend/lib/errorHandler.ts
> +      return await fetchServerSide({ path: 'auth/refresh', method: 'POST' })
внутри `checkAuthClient` уже делается запрос на refresh кук, зачем его делать, тем более когда пользователь уже авторизован?

2023-06-21 18:00 UTC, matthewTheWizzard commented on frontend/lib/errorHandler.ts
> +      return await fetchServerSide({ path: 'auth/refresh', method: 'POST' })
я так понял что приходит 401 когда нет аксесс куки, и в этом случае проверяем есть ли рефреш и если есть делаем запрос на получение. Ок, значит не так понял, перепроверю и уберу тогда все эти проверки и просто сделаю отображение ошибки

2023-06-22 19:23 UTC, kieled approved these changes

2023-06-22 19:24 UTC, merged