Users refactorin endpoints
DJWOMS/GSpot pull request #329
Opened 2023-06-19 18:02 UTC by daniilcehmestrenko

2023-06-20 05:57 UTC, gravity48 requested changes
Тесты не прошли

2023-06-20 05:57 UTC, gravity48 commented on backend/users/backend/administrator/views/v1/account_views.py
> +    permission_classes = (IsAuthenticated,)
permission class давай поставим IsAdminScopeUserPerm из модуля common.permissions.permissions

2023-06-20 05:57 UTC, gravity48 commented on backend/users/backend/customer/views/v1/account_views.py
> +    http_method_names = ('get', 'put', 'delete',)
Забыл добавить что метод put используется как patial_update, для реализации этого функционала есть mixin который находится в base.views

2023-06-20 05:57 UTC, gravity48 commented on backend/users/backend/customer/views/v1/account_views.py
> +        'DELETE': account_serializers.AccountRetrieveSerializers,
Разве на delete нужен сериалайзер?

2023-06-20 05:57 UTC, gravity48 commented on backend/users/backend/developer/views/v1/account_views.py
> +    permission_classes = (IsAuthenticated,)
Если ты добавишь правильный permission class тебе не придется определять аттрибут model. И код ответа будет уже не 404, а 403 что доступ запрещен

2023-06-20 17:40 UTC, daniilcehmestrenko commented on backend/users/backend/customer/views/v1/account_views.py
> +        'DELETE': account_serializers.AccountRetrieveSerializers,
да лишнее убрал

2023-06-20 17:40 UTC, daniilcehmestrenko commented on backend/users/backend/developer/views/v1/account_views.py
> +    permission_classes = (IsAuthenticated,)
какой пермишен нужен для developer и customer?
там есть для админов и не админов

2023-06-20 17:40 UTC, daniilcehmestrenko commented on backend/users/backend/administrator/views/v1/account_views.py
> +    permission_classes = (IsAuthenticated,)
сделал

2023-06-20 17:40 UTC, daniilcehmestrenko commented on backend/users/backend/customer/views/v1/account_views.py
> +    http_method_names = ('get', 'put', 'delete',)
сделал

2023-06-29 14:11 UTC, gravity48 requested changes
Тесты не прошли, сделай rebase, чтобы только твои изменения были видны

2023-07-15 16:38 UTC, closed without merging