Users | Features/change payloads
DJWOMS/GSpot pull request #334
Opened 2023-06-21 18:30 UTC by Edgar-84

2023-06-21 19:50 UTC, lsoulworkerl commented
Please, add name of service in name of PR

2023-06-22 12:42 UTC, gravity48 requested changes
Жду тесты на проверку функционала

2023-06-30 06:48 UTC, gravity48 approved these changes

2023-06-30 06:48 UTC, gravity48 commented on backend/users/backend/config/settings/redis_config.py
>  REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)
У нас будет два редиса, один для token класса второй для totp класса нужно добавить настройки для второго редиса

2023-06-30 06:48 UTC, merged