Frontend | auth refactor
DJWOMS/GSpot pull request #339
Opened 2023-06-25 12:13 UTC by JulieBenchuk

Использован универсальный компонент Form в SignIn, добавлен свой page.module.css. Добавлена проверка на авторизацию в header. Моковый роут за инф-цией о профиле не реализован в header (возьму следующей задачей).

2023-06-25 18:38 UTC, kieled requested changes

2023-06-25 18:38 UTC, kieled commented on frontend/app/(auth)/signin/page.tsx
> +    }
`fetchServerSide` сейчас отлавливает ошибку внутри себя, и возвращает `None`
```typescript
export const fetchServerSide = async ({path, cache = 'no-cache', ...props}) => {
  try {
    const res = await fetch(`${API_URL}${path}`, {
      ...props,
      cache,
    })

    return await res.json()
  } catch (error) {
    console.log(error)
  }
}
```
Соответвенно нужно поправить возвращаемый тип и условие

2023-06-25 18:38 UTC, kieled commented on frontend/components/Header/Header.tsx
> +  }, [])
тут нужно поспользоваться функцией `checkAuthClient` и полностью убрать `useEffect`. Т.к. компонент клиентский, нужно сделать это в компоненте на уровень выше

2023-06-27 19:54 UTC, JulieBenchuk commented on frontend/components/Header/Header.tsx
> +  }, [])
Исправила. Смущает ворнинг в консоли на отсутствие useEffect: "Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in yo
<img width="1440" alt="Снимок экрана 2023-06-27 в 22 54 25" src="https://github.com/DJWOMS/GSpot/assets/98646344/3eae99ed-8670-4210-9405-776bb9ecbe76">
ur render function that asynchronously later calls tries to update the component. Move this work to useEffect instead."

2023-06-28 07:15 UTC, kieled commented on frontend/components/Header/Header.tsx
> +  checkAuth()
это в корне не верное решение. Этот код нужно полностью отсюда убрать. Далее, в компоненте `layout` в котором используется `Header` необходимо написать код вида:
```typescript
const IsAuthenticated = checkAuthServer()
```
Компонент `layout` нужно будет сделать асинхронным, а так же результат выполнения функции нужно простым способом прокинуть в `Header` через пропсы

2023-06-28 08:10 UTC, kieled approved these changes

2023-06-28 08:10 UTC, merged