Users | Fixed conflicts, add manager
DJWOMS/GSpot pull request #38
Opened 2023-03-21 19:02 UTC by Edgar-84

2023-03-21 22:10 UTC, JustLike420 commented
Просьба: указывать название сервиса в title к pr

2023-03-22 03:47 UTC, egorFilippo requested changes

2023-03-22 03:47 UTC, egorFilippo commented on backend/users/backend/common/auth_backends.py
> +>>>>>>> d90b3a48026019cca98123d3f6bf6b31681a890e
Выглядит как нерешённый конфликт

2023-03-22 03:47 UTC, egorFilippo commented on backend/users/backend/admins/managers.py
> +class AdminQuerySet(models.QuerySet):
Где используется этот класс?

2023-03-22 08:24 UTC, kalinavladd commented on backend/users/backend/admins/managers.py
> +        return self.annotate(
Что делает Coalesce? Зачем он? и код не дописан, где тесты?

2023-03-22 14:34 UTC, Edgar-84 commented
Исправил указанные замечания по коду

2023-03-23 07:56 UTC, Edgar-84 commented
Удалил manager и все его зависимости

2023-03-23 12:38 UTC, kalinavladd approved these changes

2023-03-23 12:38 UTC, merged