BestGames component, bestgames mocksdata, bigcard component change
DJWOMS/GSpot pull request #63
Opened 2023-03-26 04:10 UTC by smnov

2023-03-26 04:56 UTC, paqstd-dev commented on frontend/components/CardBig/CardBig.tsx
> +const CardBig: FC<GameCardInterface> = ({ coverImg, badge, link, title, sale, price, available, currency = '$' }) => {
Ты мог бы сразу поменять `available` на `platforms` в интерфейсе?

2023-03-26 04:56 UTC, paqstd-dev commented on frontend/components/CardBig/CardBig.tsx
> +          {sale && <s>{[currency, price]}</s>}
В этом месте падает один из тестов. Нужно добавить в тест проверку на `currency`.

2023-03-26 04:56 UTC, paqstd-dev commented on frontend/mocks/routes/bestGames.js
Не уверен, что это работает. Нужно еще добавить в collections обработку url, например: 
```
     "id": "base",
     "routes": [
          ...,
          "best-games:success"
      ]
```

Подробнее узнать об этом можно тут https://www.mocks-server.org/docs/usage/collections/:

A collection of route variants defines all current routes and variants in the mocked API. They can be created extending other collections. So, you can store many collections and change the whole API behavior by simply changing the current one.

2023-03-26 11:38 UTC, kieled requested changes

2023-03-26 11:38 UTC, kieled commented on frontend/app/(main)/BestGames.tsx
> +  async function getData() {
функцию загрузки данных необходимо вынести за пределы компонента. И убрать useState, записывая вывод функции сразу в константу data

2023-03-28 10:09 UTC, kieled approved these changes

2023-03-28 10:11 UTC, merged