page Profile settings/purchases + styles
DJWOMS/GSpot pull request #84
Opened 2023-03-29 14:34 UTC by NikolayN-ru

2023-03-29 14:58 UTC, paqstd-dev requested changes
Файлы assets/img/breadcrumb.svg, home.svg, user.svg удалить. Доработать перенос с bootstrap на tailwind, во многих местах еще встречаются бутстраповские классы. 

Если несколько div идут подряд (в глубину), возможно стоит удалить лишние.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +import breadcrumbSVG from 'assets/img/breadcrumb.svg'
Нужно использовать [`@tabler-icons/react` библиотеку](https://github.com/tabler/tabler-icons#react) для работы с svg.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +            <div className="col-12">
Нет необходимости оборачивать в несколько div. Тем более это бутстраповские классы.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +            <div className="col-12">
Точно так же и тут. Нет необходимости это использовать.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +                </ul>
Убрать role, id, data-* атрибуты, aria-* атрибуты. Это засоряет код, но никакого эффекта не дает.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +                  </svg>
По поводу svg написал выше.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/profile.module.scss
Все классы описываются в camelCase:
```
section,
sectionWrap,
profileMeta
```
...

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/(purchasesItem)/profileItem.tsx
Лучше всего сделать отдельную feature/profile и хранить компоненты там. Например этот компонент мог бы находиться в features/profile/components/Purchases/Purchase.tsx.

Или переделать и сделать Purhcases - это таблица, а Purchase это элемент таблицы.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +                </a>
Используем `next/link` для тега `a`. 
Для svg используем @tabler/icons-react.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/page.tsx
> +}
Это вообще не используется в этом компоненте, нужно убрать.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/profileItem.test.tsx
Пока что тесты для страниц не пишем. Только для компонентов и элементов. Позже решим как лучше всего это делать.

2023-03-29 14:58 UTC, paqstd-dev commented on frontend/app/(main)/profile/settings/settings.module.scss
Работа с css modules предполагает использование одинаковых названий: 
```
page.tsx
page.module.scss
```

или 
```
ComponentA.tsx
ComponentA.module.scss
```

2023-03-29 18:08 UTC, paqstd-dev requested changes

2023-03-29 18:08 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +              ))}
Почему нельзя сделать просто, указав 
```
<th>Product <Icon /></th>
<th>...</th>
```

Не совсем понятно.

2023-03-29 18:08 UTC, paqstd-dev commented on frontend/features/profile/components/Purchases/Purchase.module.scss
> +
Пустые строки нужно удалять.

2023-03-29 18:08 UTC, paqstd-dev commented on frontend/assets/img/breadcrumb.svg
Мы не должны использовать svg так. Нужно использовать специальную библиотеку для этого.

2023-03-29 18:08 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +import { ArrowsUpDown } from 'tabler-icons-react'
```import { ArrowsUpDown } from '@tabler/icons-react'```

2023-03-29 18:52 UTC, NikolayN-ru commented on frontend/app/(main)/profile/purchases/page.tsx
> +              ))}
не сильно тут понял )
Prod1 <Icon />
Prod2 <Icon />
Prod3 <Icon />
имелось ввиду ?

2023-03-30 11:40 UTC, paqstd-dev requested changes

2023-03-30 11:40 UTC, paqstd-dev commented on frontend/assets/img/home.svg
Файл тоже нужно удалить.

2023-03-30 11:40 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +              ))}
```html
<th>Product</th>
<th>Title</th>
<th>Platform</th>
<th>Date</th>
<th>Price</th>
<th>Status</th>
```

2023-03-30 11:40 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +            ))}
Желательно сразу настроить получение mocks данных. И передавать уже полученные данные в компонент. Например: 
```
{purhases.map(purchase => <Purchase key={purchase.uid} {...purchase} />)}
```

2023-03-30 11:40 UTC, paqstd-dev commented on frontend/features/profile/components/Purchases/Purchase.tsx
> +import { X } from 'tabler-icons-react'
import { X } from '@tabler/icons-react'

У нас есть еще 'table-icons-react' модуль, его надо удалить. Видимо он был добавлен случайно.

2023-03-30 17:03 UTC, NikolayN-ru commented on frontend/app/(main)/profile/purchases/page.tsx
> +            ))}
мок сервер поменятлся / какой новый не ясно

2023-03-30 17:11 UTC, NikolayN-ru commented on frontend/app/(main)/profile/layout.tsx
> +      </section>
нельзя, кастомные иконки там не предусмотрены. только если его переделывать

2023-03-30 19:16 UTC, paqstd-dev commented on frontend/app/(main)/profile/layout.tsx
> +      </section>
Пока что не будем использовать Breadcrumbs, и необходимость в использовании иконок в этом случае отпадает

2023-03-30 19:17 UTC, paqstd-dev commented on frontend/app/(main)/profile/purchases/page.tsx
> +            ))}
Я добавил больше информации об этом в файле [CONTRIBUTING.md](https://github.com/DJWOMS/GSpot/blob/frontend/frontend/CONTRIBUTING.md#write-mocks)

2023-04-02 10:27 UTC, kieled requested changes

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      @apply w-[3px] bg-primary rounded-[4px] content-none absolute block top-[2px] bottom-[2px] left-0;
content-['']

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  @apply flex flex-col justify-start relative rounded-[6px] mb-[10px] px-[20px] pt-[20px] pb-0;
ronded-default

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  @apply flex flex-col justify-start relative rounded-[6px] mb-[10px] px-[20px] pt-[20px] pb-0;
rounded-default

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  @apply flex flex-col justify-start relative rounded-[6px] mb-[10px] px-[20px] pt-[20px] pb-0;
обращаемся к файлу tailwind.config.js и смотрим какие переменные там указаны, чтобы не использовать квадратные скобки

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      @apply text-white text-base scale-[.8] leading-[100%] leading-[100%];
scale-80

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        @apply absolute bottom-0 left-0 right-0 h-[2px] block bg-primary opacity-0;
content-['']

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        content: '';
эту строчку везде надо убрать. и заменить на вариант tailwind

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +    @apply flex justify-center items-center w-[44px] h-[44px] rounded-[6px] text-white absolute top-[20px] right-[20px] uppercase text-xs;
rounded-default

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +    background-color: rgba(167,130,233,0.03);
в tailwind.config.js есть этот цвет

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      border-bottom: 1px solid rgba(167,130,233,0.06);
тут почему-то пропущена стилизация tailwind

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      padding: 10px 20px 20px;
pt-[10px] px-[20px] pb-[20px]

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      font-size: 16px;
text-base

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      font-weight: 400;
font-normal

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      padding: 10px 20px 10px 0;
как и выше с паддингами

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        border-bottom: 2px dotted #a782e9;
border-b-2 border-dotted text-[14px]

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        padding: 10px 20px;
py-[10px] px-[20px]

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        padding: 10px 20px;
снова паддинги

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +      }
тут написал tailwind но не удалил css стили

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +            @apply pt-[20px] pr-[20px] pb-[10px] pl-[20px];
вместо pr и pl можно писать px-

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +        @apply pt-[20px] pr-[20px] pb-[20px] pl-0;
вместо pt и pb- можно писать py-

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +            @apply pt-[20px] pr-[20px] pb-[10px] pl-[20px];
тоже самое как и выше px- вместо pr и pl

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +          @apply pt-[10px] pr-[20px] pb-[20px] pl-[0px];
аналогично

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  @apply bg-background p-[20px] rounded-[6px] mt-[30px];
rounded-default

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  background-color: #1b222e;
этот цвет тоже есть в tailwind.config.js

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +  border: 1px solid rgba(167,130,233,0.06);
border border-итутцвет

2023-04-02 10:27 UTC, kieled commented on frontend/app/(main)/profile/layout.module.scss
> +    letter-spacing: 0.4px;
tracking-[.4px]

2023-04-10 04:13 UTC, paqstd-dev approved these changes

2023-04-10 09:04 UTC, kieled approved these changes

2023-04-10 14:52 UTC, merged